import React, { useEffect, useRef, useState } from 'react';
import { BarChart3, TrendingUp, Download, RefreshCw, Plus, Pencil, X, Check, AlertCircle, ArrowDownLeft, ArrowUpRight } from 'lucide-react';
import { halls, hallColors, money as currency, today, fmtDate, iso } from './models';
import './analytics.css';

const query = data => new URLSearchParams(Object.fromEntries(Object.entries(data).map(([k,v]) => [k, typeof v === 'boolean' ? (v ? '1' : '0') : v]))).toString();
const money = value => currency(value).replace(/\s*DT$/, '');
function ErrorBox({ error }) { return error ? <div className="error-box" role="alert"><AlertCircle size={18} />{error}</div> : null; }
function Input({ label, children }) { return <label className="field"><span>{label}</span>{children}</label>; }
function Stats({ cards }) { return <div className="stats-grid finance-stats">{cards.map(([label, value, note, color]) => <div className="stat" key={label}><span>{label}</span><div><b className={color}>{value}</b></div><small>{note}</small></div>)}</div>; }
function Table({ headers, rows, empty = 'Aucun mouvement sur cette période.' }) { return <div className="finance-table"><table><thead><tr>{headers.map(h => <th key={h}>{h}</th>)}</tr></thead><tbody>{rows.length ? rows.map((cells, i) => <tr key={i}>{cells.map((cell,j) => <td key={j}>{cell}</td>)}</tr>) : <tr><td colSpan={headers.length}><div className="empty">{empty}</div></td></tr>}</tbody></table></div>; }
function Tabs({ value, set, options }) { return <div className="finance-tabs" role="tablist">{options.map(([key,label]) => <button role="tab" aria-selected={value === key} className={value === key ? 'selected' : ''} onClick={() => set(key)} key={key}>{label}</button>)}</div>; }
function Notes({ children, warnings = [] }) { return <div className="finance-note">{children}{warnings.map(w => <p key={w} className="amber">{w}</p>)}</div>; }
function Bars({ data, field = 'booked' }) {
  const max = Math.max(1, ...data.map(r => r[field]));
  return <div className="finance-bars">{data.length ? data.map((r,i) => <div key={r.name}><div><span>{r.name}</span><b>{money(r[field])} <small>DT</small></b></div><div className="finance-track"><i style={{ width: `${Math.max(0,r[field])/max*100}%`, background: hallColors[r.name] || ['#387b6e','#ae937b','#83a9b9'][i%3] }} /></div><small>{r.count} {field === 'amount' ? 'acompte(s)' : 'réservation(s)'}</small></div>) : <p className="muted">Aucune donnée dans la période.</p>}</div>;
}
function BalanceChart({ data }) {
  const [hover,setHover] = useState(null);
  const points = [{ label: 'Ouverture', closing: data.parameters.opening }, ...data.periods];
  const values = points.map(p => p.closing), lo = Math.min(0,data.parameters.floor,...values), hi = Math.max(1,data.parameters.floor,...values);
  const y = n => 192 - (n-lo)/(hi-lo)*156, x = i => 66+i*640/Math.max(1,points.length-1);
  const line = points.map((p,i) => `${x(i)},${y(p.closing)}`).join(' ');
  const shown = hover === null ? points[points.length-1] : points[hover];
  return <div className="balance-chart"><div className="chart-readout"><span>{shown.label === 'Ouverture' ? 'Solde initial' : `${fmtDate(shown.start)} → ${fmtDate(shown.end)}`}</span><b className={shown.closing < 0 ? 'red' : 'green'}>{money(shown.closing)} DT</b></div><svg viewBox="0 0 760 235" role="img" aria-label="Évolution du solde prévu à la clôture de chaque période"><defs><linearGradient id="cash-shade" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#387b6e" stopOpacity=".16" /><stop offset="1" stopColor="#387b6e" stopOpacity=".01" /></linearGradient></defs>{[0,.5,1].map(r => { const n = lo+(hi-lo)*r; return <g key={r}><line x1="66" x2="706" y1={y(n)} y2={y(n)} stroke="#edf0f1" /><text x="58" y={y(n)+4} textAnchor="end" fontSize="10" fill="#8d9b9d">{Math.round(n).toLocaleString('fr-FR')}</text></g>; })}<line x1="66" x2="706" y1={y(data.parameters.floor)} y2={y(data.parameters.floor)} stroke="#bd985e" strokeDasharray="5 5" /><polygon points={`66,${y(0)} ${line} 706,${y(0)}`} fill="url(#cash-shade)" /><polyline points={line} fill="none" stroke="#387b6e" strokeWidth="2.5" strokeLinejoin="round" />{points.map((p,i) => <g key={i} onMouseEnter={() => setHover(i)} onMouseLeave={() => setHover(null)}><circle cx={x(i)} cy={y(p.closing)} r="14" fill="transparent" /><circle cx={x(i)} cy={y(p.closing)} r={hover === i ? 5 : 3} fill={p.closing < 0 ? '#bc6270' : '#387b6e'} /><title>{p.label} : {money(p.closing)} DT</title>{(points.length <= 9 || i%Math.ceil(points.length/8) === 0 || i === points.length-1) && <text x={x(i)} y="222" textAnchor="middle" fill="#8d9b9d" fontSize="10">{i === 0 ? 'Départ' : data.parameters.group === 'week' ? fmtDate(p.start).slice(0,5) : p.label}</text>}</g>)}</svg><div className="chart-legend"><span><i />Solde de fin de période</span><span><i className="threshold" />Seuil de sécurité : {money(data.parameters.floor)} DT</span></div></div>;
}

export function AdvancedReports({ api, saveFile, notify }) {
  const [filters,setFilters] = useState({ start: today().slice(0,8)+'01', end: today(), hall: 'all' });
  const [data,setData] = useState(null), [tab,setTab] = useState('overview'), [error,setError] = useState(''), [busy,setBusy] = useState(false);
  const sequence = useRef(0);
  async function load(params = filters) { const id = ++sequence.current; setBusy(true); setError(''); try { const value = await api('/reports?'+query(params)); if (id === sequence.current) setData(value); } catch(e) { if(id === sequence.current) setError(e.message); } finally { if(id === sequence.current) setBusy(false); } }
  useEffect(() => { load(); return () => { sequence.current++; }; }, []);
  async function exportExcel() { setBusy(true); setError(''); try { const result = await saveFile(await api('/exports/reports?'+query(data.period))); if (!result.canceled) notify('Rapports Excel enregistrés.'); } catch(e) { setError(e.message); } finally { setBusy(false); } }
  const dirty = data && query(filters) !== query(data.period);
  function preset(kind) { const now = new Date(), start = new Date(now.getFullYear(), kind === 'year' ? 0 : kind === 'quarter' ? Math.floor(now.getMonth()/3)*3 : now.getMonth(), 1); const value = { ...filters,start: iso(start),end: today() }; setFilters(value); load(value); }
  return <div className="finance-module"><div className="page-intro"><div><small className="eyebrow">PILOTAGE DE VOTRE ACTIVITÉ</small><h1>Rapports avancés<span>.</span></h1><p className="muted">Réservations, encaissements, caisses et équipe dans une seule vue.</p></div><button className="primary" disabled={!data || busy || dirty} onClick={exportExcel}><Download size={17} />Exporter les rapports</button></div><form className="panel finance-filters" onSubmit={e => { e.preventDefault(); load(); }}><Input label="Du"><input type="date" required value={filters.start} onChange={e => setFilters({ ...filters,start:e.target.value })} /></Input><Input label="Au"><input type="date" required value={filters.end} onChange={e => setFilters({ ...filters,end:e.target.value })} /></Input><Input label="Salle · réservations et acomptes"><select value={filters.hall} onChange={e => setFilters({ ...filters,hall:e.target.value })}><option value="all">Toutes les salles</option>{halls.map(h => <option key={h}>{h}</option>)}</select></Input><button className="secondary" disabled={busy}><RefreshCw size={16} className={busy ? 'spin' : ''} />Actualiser</button><div className="finance-presets">{[['month','Ce mois'],['quarter','Trimestre'],['year','Année']].map(([k,l]) => <button type="button" disabled={busy} key={k} onClick={() => preset(k)}>{l}</button>)}</div></form><ErrorBox error={error} />{dirty && <Notes>Filtres modifiés : actualisez pour afficher et exporter cette sélection.</Notes>}{data && <><div className="finance-caption">Événements du {fmtDate(data.period.start)} au {fmtDate(data.period.end)} · {data.period.hall === 'all' ? 'Toutes les salles' : data.period.hall} · Soldes actuels au {fmtDate(data.asOf)}</div><Stats cards={[
    ['Forfaits des événements',money(data.summary.booked)+' DT',`${data.summary.count} bons confirmés · ${data.summary.temporaryCount} option(s) exclue(s)`],
    ['Acomptes sur ces bons',money(data.summary.paid)+' DT','Tous les acomptes enregistrés sur les bons sélectionnés'],
    ['Solde restant actuel',money(data.summary.outstanding)+' DT',`${money(data.summary.overdue)} DT échus à J−15`,'amber'],
    ['Acomptes datés de la période',money(data.summary.deposits)+' DT','Selon la date de paiement, tous événements confondus','green']
  ]} /><Tabs value={tab} set={setTab} options={[[ 'overview','Synthèse'],['halls','Salles & événements'],['outstanding','Soldes à encaisser'],['cash','Caisses'],['employees','Employés'],['methods','Modes de paiement']]} />
  {tab === 'overview' && <><div className="finance-grid"><section className="panel finance-card"><div className="finance-card-title"><BarChart3 size={19} /><h2>Activité par salle</h2><small>Forfaits · DT</small></div><Bars data={data.halls} /></section><section className="panel finance-card comparison-card"><small className="eyebrow">COMPARAISON À DURÉE ÉGALE</small><h2>{data.summary.changePercent === null ? 'Première période de référence' : `${data.summary.changePercent > 0 ? '+' : ''}${data.summary.changePercent} %`}</h2><p className="muted">Évolution des forfaits par rapport au {fmtDate(data.previousPeriod.start)} – {fmtDate(data.previousPeriod.end)}.</p><div><span>Période actuelle<b>{money(data.summary.booked)} DT</b><small>{data.summary.count} bons</small></span><span>Période précédente<b>{money(data.summary.previousBooked)} DT</b><small>{data.summary.previousCount} bons</small></span></div>{data.summary.changePercent === null && <small>La période précédente ne contient aucun forfait : pourcentage non calculable.</small>}</section></div><section className="panel"><div className="finance-card-title padded"><TrendingUp size={19} /><h2>Lecture mensuelle</h2></div><Table headers={['Mois','Bons confirmés','Forfaits · DT','Acomptes datés · DT']} rows={data.monthly.map(r => [r.month,r.count,money(r.booked),money(r.deposits)])} /></section></>}
  {tab === 'halls' && <><section className="panel"><Table headers={['Salle','Bons','Forfaits · DT','Acomptes · DT','Reste actuel · DT','Forfait moyen · DT']} rows={data.halls.map(r => [<b>{r.name}</b>,r.count,money(r.booked),money(r.paid),money(r.outstanding),money(r.average)])} /></section><section className="panel"><div className="finance-card-title padded"><h2>Types d’événements</h2></div><Table headers={['Événement','Bons','Forfaits · DT']} rows={data.types.map(r => [r.name,r.count,money(r.booked)])} /></section></>}
  {tab === 'outstanding' && <section className="panel"><Table headers={['Bon / client','Salle','Événement','Échéance J−15','Reste · DT','État']} rows={data.outstanding.map(r => [<><b>{r.bon}</b><small className="cell-note">{r.client}</small></>,r.hall,fmtDate(r.event),fmtDate(r.due),<b>{money(r.remaining)}</b>,<span className={`status-pill ${r.overdueDays ? 'amber' : 'green'}`}>{r.overdueDays ? `${r.overdueDays} j de retard` : 'À venir'}</span>])} empty="Tous les bons sélectionnés sont soldés." /></section>}
  {tab === 'cash' && <section className="panel"><div className="finance-card-title padded"><h2>Caisses · toutes salles</h2></div><Table headers={['Caisse','Recettes · DT','Sorties · DT','Solde des mouvements · DT']} rows={data.cash.map(r => [<b>{r.name}</b>,money(r.income),money(r.expense),<b className={r.net < 0 ? 'red' : 'green'}>{money(r.net)}</b>])} /><Notes>Ces chiffres reprennent les journaux existants. Le filtre de salle ne s’applique pas aux caisses. Le solde des mouvements ne représente pas le bénéfice.</Notes></section>}
  {tab === 'employees' && <section className="panel"><Table headers={['Employé','Type','Jours / périodes','HS','Tarifs période · DT','Payé période · DT','Reste global · DT']} rows={data.employees.map(r => [r.name,r.type,`${r.days} / ${r.periods}`,r.hours,money(r.earned),money(r.paid),money(r.globalRemaining)])} /><Notes>Pointages et paiements de la période, toutes salles. Les montants de pointage utilisent les tarifs actuels. Le reste global couvre toute la fiche employé.</Notes></section>}
  {tab === 'methods' && <section className="panel"><Table headers={['Mode de paiement','Nombre d’acomptes','Montant daté · DT']} rows={data.methods.map(r => [r.name,r.count,money(r.amount)])} /></section>}
  <Notes warnings={data.warnings}>Les forfaits suivent la date de l’événement ; les encaissements suivent la date de l’acompte. Les soldes reflètent les paiements enregistrés à ce jour.</Notes></>}</div>;
}

export function CashForecast({ api, saveFile, notify, Modal }) {
  const [data,setData] = useState(null), [params,setParams] = useState(null), [tab,setTab] = useState('forecast'), [error,setError] = useState(''), [busy,setBusy] = useState(false), [form,setForm] = useState(null), [formError,setFormError] = useState(''), [all,setAll] = useState(false);
  const sequence = useRef(0), settingsKey = useRef(crypto.randomUUID()), itemKey = useRef(crypto.randomUUID());
  async function load(values, reset = false) { const id = ++sequence.current; setBusy(true); setError(''); try { const value = await api('/forecast'+(values ? '?'+query(values) : '')); if(id === sequence.current) { setData(value); if(!values || reset) setParams(value.parameters); } } catch(e) { if(id === sequence.current) setError(e.message); } finally { if(id === sequence.current) setBusy(false); } }
  useEffect(() => { load(); return () => { sequence.current++; }; }, []);
  const change = (k,v) => { settingsKey.current = crypto.randomUUID(); setParams(p => ({ ...p,[k]:v })); };
  const dirty = data && params && query(params) !== query(data.parameters);
  async function saveSettings() { setBusy(true); setError(''); try { const settings = await api('/forecast/settings',{ method:'PUT',idempotencyKey:settingsKey.current,body:{ opening_date:params.start,opening_balance:params.opening,safety_floor:params.floor,collection_rate:params.rate,revision:data.settings.revision }}); setData(d => ({ ...d,settings })); settingsKey.current = crypto.randomUUID(); notify('Hypothèses partagées enregistrées.'); await load(params); } catch(e) { setError(e.message); } finally { setBusy(false); } }
  function edit(item) { itemKey.current = crypto.randomUUID(); setFormError(''); setForm(item || { due_date:params.start,designation:'',direction:'out',amount:'',category:'Autre',frequency:'once',repeat_until:'',state:'planned' }); }
  const changeItem = (k,v) => { itemKey.current = crypto.randomUUID(); setForm(f => ({ ...f,[k]:v })); };
  async function saveItem(e) { e.preventDefault(); setBusy(true); setFormError(''); try { const body = Object.fromEntries(['due_date','designation','direction','amount','category','frequency','repeat_until','state'].map(k => [k,form[k]])); if(form.id) body.revision = form.revision; if(body.frequency === 'once') body.repeat_until = null; await api('/forecast-items'+(form.id ? '/'+form.id : ''),{ method:form.id ? 'PUT':'POST',body,idempotencyKey:itemKey.current }); setForm(null); notify('Mouvement prévu enregistré.'); await load(data.parameters); } catch(e) { setFormError(e.message); } finally { setBusy(false); } }
  async function exportExcel() { setBusy(true); setError(''); try { const result = await saveFile(await api('/exports/forecast?'+query(data.parameters))); if(!result.canceled) notify('Prévision Excel enregistrée.'); } catch(e) { setError(e.message); } finally { setBusy(false); } }
  return <div className="finance-module"><div className="page-intro"><div><small className="eyebrow">ANTICIPER VOTRE TRÉSORERIE</small><h1>Cash-flow prévu<span>.</span></h1><p className="muted">Soldes des réservations à J−15 et mouvements que vous planifiez.</p></div><button className="primary" disabled={!data || busy || dirty} onClick={exportExcel}><Download size={17} />Exporter la prévision</button></div><ErrorBox error={error} />{params && <form className="panel forecast-controls" onSubmit={e => { e.preventDefault(); load(params); }}><div className="forecast-control-heading"><h2>Hypothèses de prévision</h2><button type="button" className="text-link" disabled={busy} onClick={() => load(undefined,true)}><RefreshCw size={14} />Recharger les valeurs partagées</button></div><div className="finance-filters"><Input label="Date du solde initial"><input type="date" required value={params.start} onChange={e => change('start',e.target.value)} /></Input><Input label="Prévoir jusqu’au"><input type="date" min={params.start} required value={params.end} onChange={e => change('end',e.target.value)} /></Input><Input label="Solde initial · DT"><input type="number" step="0.001" required value={params.opening} onChange={e => change('opening',e.target.value)} /></Input><Input label="Seuil de sécurité · DT"><input type="number" step="0.001" min="0" required value={params.floor} onChange={e => change('floor',e.target.value)} /></Input><Input label="Recouvrement des soldes · %"><input type="number" min="0" max="100" step="1" required value={params.rate} onChange={e => change('rate',e.target.value)} /></Input><Input label="Vue"><select value={params.group} onChange={e => change('group',e.target.value)}><option value="month">Mensuelle</option><option value="week">Hebdomadaire</option></select></Input></div><div className="forecast-controls-footer"><label className="check-field"><input type="checkbox" checked={params.overdue} onChange={e => change('overdue',e.target.checked)} />Inclure les soldes déjà échus au début de période</label><div className="inline-controls"><button className="secondary" disabled={busy}><RefreshCw size={15} className={busy ? 'spin' : ''} />Calculer</button><button type="button" className="primary" disabled={busy} onClick={saveSettings}><Check size={15} />Enregistrer les hypothèses</button></div></div><Notes>Le solde initial est votre trésorerie disponible à la date choisie. Le taux s’applique uniquement aux soldes de réservation. Date, solde, seuil et taux enregistrés sont partagés entre les postes.</Notes></form>}{dirty && <Notes>Hypothèses modifiées : cliquez sur Calculer pour mettre à jour la prévision.</Notes>}{data && <><div className="finance-caption">Prévision du {fmtDate(data.parameters.start)} au {fmtDate(data.parameters.end)} · Recouvrement {data.parameters.rate} % · Situation des réservations à ce jour</div><Stats cards={[
    ['Entrées prévues',money(data.summary.income)+' DT','Soldes restant dus + entrées planifiées','green'],
    ['Sorties prévues',money(data.summary.expense)+' DT','Dépenses planifiées dans ce module'],
    ['Solde final prévu',money(data.summary.closing)+' DT',`Au ${fmtDate(data.parameters.end)}`,data.summary.closing < 0 ? 'red':'green'],
    ['Solde quotidien minimum',money(data.summary.lowest)+' DT',`Le ${fmtDate(data.summary.lowestDate)}`,data.summary.lowest < data.parameters.floor ? 'amber':undefined]
  ]} />{(data.summary.negativeDate || data.summary.floorDate) && <div className={`forecast-alert ${data.summary.negativeDate ? 'negative' : ''}`}><AlertCircle size={19} /><div><b>{data.summary.negativeDate ? `Trésorerie négative prévue dès le ${fmtDate(data.summary.negativeDate)}` : `Seuil de sécurité franchi le ${fmtDate(data.summary.floorDate)}`}</b><p>Minimum quotidien : {money(data.summary.lowest)} DT. Vérifiez les échéances et les dépenses planifiées.</p></div></div>}<Tabs value={tab} set={setTab} options={[[ 'forecast','Prévision de trésorerie'],['events',`Échéancier (${data.events.length})`],['plans','Mouvements planifiés']]} />
  {tab === 'forecast' && <><section className="panel finance-card"><div className="finance-card-title"><TrendingUp size={19} /><h2>Évolution de votre trésorerie</h2><small>DT · {data.parameters.group === 'week' ? 'par semaine':'par mois'}</small></div><BalanceChart data={data} /></section><section className="panel"><Table headers={['Période','Ouverture · DT','Entrées · DT','Sorties · DT','Variation · DT','Solde prévu · DT']} rows={data.periods.map(r => [`${fmtDate(r.start)} → ${fmtDate(r.end)}`,money(r.opening),<span className="green">{money(r.income)}</span>,money(r.expense),money(r.net),<b className={r.closing < 0 ? 'red':'green'}>{money(r.closing)}</b>])} /></section></>}
  {tab === 'events' && <section className="panel"><Table headers={['Date prévue / échéance','Désignation','Origine','Entrée · DT','Sortie · DT']} rows={data.events.map(r => [<>{fmtDate(r.date)}{r.late && <small className="cell-note amber">Échu le {fmtDate(r.due)} · date de recouvrement supposée</small>}</>,<>{r.designation}{r.amount !== r.nominal && <small className="cell-note">Solde nominal : {money(r.nominal)} DT</small>}</>,<span className={`status-pill ${r.source === 'reservation' ? 'green':'gray'}`}>{r.source === 'reservation' ? `Réservation · ${r.hall}`:'Planifié'}</span>,r.direction === 'in' ? money(r.amount):'—',r.direction === 'out' ? money(r.amount):'—'])} /></section>}
  {tab === 'plans' && <section className="panel"><div className="finance-card-title padded"><h2>Vos mouvements prévus</h2><label className="check-field"><input type="checkbox" checked={all} onChange={e => setAll(e.target.checked)} />Voir réalisés et annulés</label><button className="primary compact" disabled={busy} onClick={() => edit()}><Plus size={15} />Ajouter un mouvement</button></div><Table headers={['Échéance','Désignation','Sens / montant · DT','Répétition','État','']} rows={data.items.filter(r => all || r.state === 'planned').map(r => [fmtDate(r.due_date),<><b>{r.designation}</b><small className="cell-note">{r.category}</small></>,<span className={r.direction === 'in' ? 'green':'red'}>{r.direction === 'in' ? '+':'−'} {money(r.amount)}</span>,r.frequency === 'monthly' ? <>Chaque mois<small className="cell-note">Jusqu’au {fmtDate(r.repeat_until)}</small></>:'Une fois',<span className={`status-pill ${r.state === 'planned' ? 'amber':'gray'}`}>{r.state === 'planned' ? 'Prévu':r.state === 'settled' ? 'Réalisé':'Annulé'}</span>,<button className="icon-button" aria-label={`Modifier ${r.designation}`} disabled={busy} onClick={() => edit(r)}><Pencil size={16} /></button>])} empty="Planifiez vos charges, salaires et autres entrées ou sorties." /><Notes>Un mouvement réalisé ou annulé est retiré de la prévision. Le statut ne crée aucun paiement dans les caisses ou les fiches employés. Une série mensuelle est gérée dans son ensemble.</Notes></section>}
  <Notes warnings={data.warnings}>Les dépenses futures sont à renseigner dans « Mouvements planifiés ». Les acomptes et charges déjà enregistrés ne sont pas ajoutés une seconde fois. {data.parameters.overdue && data.summary.overdue > 0 && <p>{money(data.summary.overdue)} DT de soldes échus sont inclus au {fmtDate(data.parameters.start)} avant application du taux : cette date est une hypothèse de recouvrement.</p>}</Notes></>}{form && <Modal title={form.id ? 'Modifier le mouvement prévu':'Planifier un mouvement'} close={() => { if(!busy) setForm(null); }}><form onSubmit={saveItem}><div className="modal-body"><ErrorBox error={formError} /><div className="fields-grid"><Input label="Désignation"><input required value={form.designation} onChange={e => changeItem('designation',e.target.value)} /></Input><Input label="Échéance / première date"><input type="date" required value={form.due_date} onChange={e => changeItem('due_date',e.target.value)} /></Input><Input label="Sens"><select value={form.direction} onChange={e => changeItem('direction',e.target.value)}><option value="out">Sortie prévue</option><option value="in">Entrée prévue</option></select></Input><Input label="Montant · DT"><input type="number" step="0.001" min="0.001" required value={form.amount} onChange={e => changeItem('amount',e.target.value)} /></Input><Input label="Catégorie"><select value={form.category} onChange={e => changeItem('category',e.target.value)}>{['Autre','Loyer','Salaires','Fournisseurs','Énergie','Entretien','Financement'].map(c => <option key={c}>{c}</option>)}</select></Input><Input label="Répétition"><select value={form.frequency} onChange={e => changeItem('frequency',e.target.value)}><option value="once">Une fois</option><option value="monthly">Chaque mois</option></select></Input>{form.frequency === 'monthly' && <Input label="Répéter jusqu’au"><input type="date" min={form.due_date} required value={form.repeat_until || ''} onChange={e => changeItem('repeat_until',e.target.value)} /></Input>}<Input label={form.frequency === 'monthly' ? 'État de toute la série':'État'}><select value={form.state} onChange={e => changeItem('state',e.target.value)}><option value="planned">Prévu</option><option value="settled">Réalisé</option><option value="cancelled">Annulé</option></select></Input></div><Notes>Pour une répétition au 31, les mois plus courts utilisent leur dernier jour. Les occurrences antérieures au début de la prévision sont exclues. En cas de conflit, fermez puis rechargez avant de modifier.</Notes></div><div className="modal-footer"><button type="button" className="secondary" disabled={busy} onClick={() => setForm(null)}>Annuler</button><button className="primary" disabled={busy}><Check size={16} />Enregistrer</button></div></form></Modal>}</div>;
}
