export const halls = ['Almes', 'Chichkhane', 'Rayhane'];
export const hallColors = { Almes: '#4883db', Chichkhane: '#d97485', Rayhane: '#459e80' };
export const money = value => new Intl.NumberFormat('fr-TN', { minimumFractionDigits: 3, maximumFractionDigits: 3 }).format(Number(value || 0)) + ' DT';
export const paid = row => [1, 2, 3].reduce((sum, n) => sum + Number(row[`acompte${n}`] || 0), 0);
export const iso = value => { const d = new Date(value); return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`; };
export const today = () => iso(new Date());
export const fmtDate = value => value ? new Date(value + 'T12:00:00').toLocaleDateString('fr-FR') : '—';
const f = (key, label, type = 'text', options, required = false) => ({ key, label, type, options, required });
export const reservationSections = [
  ['Événement & créneau', [f('date_evenement', 'Date de l’événement', 'date', null, true), f('heure_debut', 'Heure de début', 'time', null, true), f('heure_fin', 'Heure de fin', 'time', null, true), f('type_evenement', 'Type d’événement'), f('nb_places', 'Nombre de places', 'number'), f('blocage_journee', 'Blocage journée', 'checkbox'), f('is_temporaire', 'Réservation temporaire', 'checkbox')]],
  ['Informations client', [f('nom_client', 'Nom du client', 'text', null, true), f('cin', 'N° CIN'), f('date_cin', 'Date de délivrance CIN', 'date'), f('lieu_cin', 'Lieu de délivrance CIN'), f('tel1', 'Téléphone principal', 'tel'), f('tel2', 'Deuxième téléphone', 'tel'), f('lieu_contrat', 'Adresse / lieu du contrat'), f('date_contrat', 'Date du contrat', 'date'), f('heure_contrat', 'Heure du contrat', 'time'), f('date_signature', 'Date de signature', 'date'), f('n_facture', 'N° facture')]],
  ['Forfait & paiement', [f('forfait_type', 'Type de forfait', 'select', ['Forfait', 'Extra']), f('forfait', 'Forfait (DT)', 'number'), f('methode_paiement', 'Méthode de paiement', 'select', ['Espèce', 'Chèque', 'Virement', 'Effet']), f('caisse', 'Caisse'), f('tresorerie', 'Trésorerie'), f('reste_acompte', 'Reste d’acompte (DT)', 'number'), f('date_reste', 'Date du reste', 'date'), f('num_cheque_virement', 'N° chèque / virement / effet'), f('banque', 'Banque'), f('date_cheque_virement', 'Date chèque / virement / effet', 'date'), f('statut_paiement', 'Statut paiement'), f('details_extra', 'Détails extra', 'textarea')]],
  ['Options & violoniste', [f('with_violoniste', 'Heure de violoniste', 'checkbox'), f('with_sono', 'Sonorisation', 'checkbox'), f('violoniste_date', 'Date Rayhane / violoniste', 'date'), f('violoniste_heure_debut', 'Début violoniste', 'time'), f('violoniste_heure_fin', 'Fin violoniste', 'time'), f('opt_espace_gazon', 'Espace gazon', 'checkbox'), f('opt_tourniquet', 'Tourniquet', 'checkbox'), f('opt_logiciel', 'Logiciel d’organisation', 'checkbox'), f('opt_invitations', 'Invitations', 'checkbox')]],
  ...[1, 2, 3].map(n => [`Acompte ${n}`, [f(`acompte${n}`, 'Montant (DT)', 'number'), f(`date_acompte${n}`, 'Date d’acompte', 'date'), f(`methode_acompte${n}`, 'Méthode', 'select', ['Espèce', 'Chèque', 'Virement', 'Effet']), f(`fn${n}`, 'FN° / N° de pièce'), f(`num_caisse${n}`, 'N° Caisse Tawfik'), f(`num_caisse_omar${n}`, 'Montant Caisse Omar (DT)')]])
];
export const schemas = {
  charges: { label: 'Charges', permission: 'Charges', fields: [f('date_encaissement', 'Date', 'date', null, true), f('designation', 'Désignation', 'text', null, true), f('montant', 'Montant (DT)', 'number', null, true)], columns: ['date_encaissement', 'designation', 'montant'] },
  'charges-omar': { label: 'Charges Omar', permission: 'Charges Omar', fields: [f('date_encaissement', 'Date', 'date', null, true), f('designation', 'Désignation', 'text', null, true), f('montant', 'Montant (DT)', 'number', null, true)], columns: ['date_encaissement', 'designation', 'montant'] },
  'recettes-omar': { label: 'Recettes Omar', permission: 'Journal Caisse Omar', fields: [f('date_recette', 'Date', 'date', null, true), f('designation', 'Désignation', 'text', null, true), f('montant', 'Montant (DT)', 'number', null, true)], columns: ['date_recette', 'designation', 'montant'] },
  employees: { label: 'Liste employés', permission: 'Liste employés', createPermission: 'Ajouter employé', fields: [f('nom', 'Nom', 'text', null, true), f('prenom', 'Prénom', 'text', null, true), f('role', 'Rôle / poste', 'text', null, true), f('icone', 'Icône'), f('type_ouvrier', 'Type d’ouvrier', 'select', ['jour', 'nuit']), f('salaire_journalier', 'Salaire journalier (DT)', 'number'), f('prix_heure_supp', 'Prix heure supplémentaire (DT)', 'number'), f('salaire_midi', 'Salaire midi (DT)', 'number'), f('salaire_apres_midi', 'Salaire après-midi (DT)', 'number'), f('salaire_soiree', 'Salaire soirée (DT)', 'number'), f('salaire_minimum', 'Salaire minimum (DT)', 'number'), f('actif', 'Actif', 'checkbox')], columns: ['nom', 'prenom', 'role', 'type_ouvrier', 'salaire_journalier', 'actif'] },
  pointage: { label: 'Pointage', permission: 'Pointage', fields: [f('employee_id', 'Employé', 'employee', null, true), f('date_pointage', 'Date', 'date', null, true), f('heure_arrivee', 'Heure d’arrivée', 'time'), f('heure_depart', 'Heure de départ', 'time'), f('periode', 'Période', 'select', ['midi', 'apres_midi', 'soiree', 'journee_complete']), f('heures_supplementaires', 'Heures supplémentaires', 'number'), f('notes', 'Notes', 'textarea')], columns: ['employee_id', 'date_pointage', 'periode', 'heure_arrivee', 'heure_depart', 'heures_supplementaires'] },
  'employee-payments': { label: 'Paiements employés', permission: 'Liste employés', fields: [f('employee_id', 'Employé', 'employee', null, true), f('date_paiement', 'Date de paiement', 'date', null, true), f('periode_debut', 'Période du', 'date', null, true), f('periode_fin', 'Période au', 'date', null, true), f('montant_base', 'Montant de base (DT)', 'number'), f('montant_heures_supp', 'Heures supplémentaires (DT)', 'number'), f('montant_total', 'Total payé (DT)', 'number', null, true), f('notes', 'Notes', 'textarea')], columns: ['employee_id', 'date_paiement', 'periode_debut', 'periode_fin', 'montant_total'] },
  rules: { label: 'Règles de réservation', permission: 'Règles de réservation', fields: [f('nom', 'Nom de la règle', 'text', null, true), f('salle', 'Salle', 'select', [...halls, '*']), f('date_debut', 'Période du', 'date'), f('date_fin', 'Période au', 'date'), f('jours', 'Jours (0=lundi, 6=dimanche)'), f('creneaux', 'Créneaux (15:00-18:00;21:00-01:00)'), f('pause_min_heures', 'Pause minimale (heures)', 'number'), f('heure_fin_max', 'Heure de fin maximale', 'time'), f('sono_obligatoire', 'Sono obligatoire', 'checkbox'), f('violon_gratuit', 'Violon gratuit', 'checkbox'), f('violon_debut_min', 'Début minimum violon', 'time'), f('violon_fin_max', 'Fin maximum violon', 'time'), f('violon_duree_max', 'Durée maximum violon (heures)', 'number'), f('violon_pause_heures', 'Pause violon (heures)', 'number'), f('priorite', 'Priorité', 'number'), f('actif', 'Active', 'checkbox'), f('notes', 'Notes', 'textarea')], columns: ['nom', 'salle', 'date_debut', 'date_fin', 'creneaux', 'actif'] }
};
export function initialFields(fields) {
  return Object.fromEntries(fields.map(field => [field.key, field.type === 'checkbox' ? (field.key === 'actif' ? 1 : 0) : field.type === 'select' ? field.options[0] : field.type === 'date' && !['date_debut', 'date_fin'].includes(field.key) ? today() : field.type === 'number' ? 0 : '']));
}
