import React,{useEffect,useState} from 'react';
import { Cloud,RefreshCw,Check,Clock3 } from 'lucide-react';
export function OnlineSync({call,notify,config}){
  const [state,setState]=useState(null),[url,setUrl]=useState(''),[secret,setSecret]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  async function load(){try{const value=await call('onlineStatus');setState(value);if(value.onlineUrl)setUrl(value.onlineUrl);}catch(e){setError(e.message);}}
  useEffect(()=>{load();const timer=setInterval(load,20000);return()=>clearInterval(timer);},[]);
  if(config.mode!=='client')return <section className="panel replica-settings"><h2>Copie en ligne · Vercel</h2><p className="muted">Activez le relais sur l’un des quatre postes qui dispose d’Internet. Ce serveur peut rester hors ligne.</p></section>;
  async function work(fn,message){setBusy(true);setError('');try{await fn();setSecret('');notify(message);await load();}catch(e){setError(e.message);}finally{setBusy(false);}}
  return <section className="panel replica-settings online-settings"><div className="card-heading"><Cloud size={22}/><h2>Synchronisation en ligne</h2><span className="status-pill green">Toutes les 20 min</span></div><p className="muted">Ce poste envoie une copie du serveur vers votre site Vercel en consultation uniquement. Vous pouvez activer un autre relais sur un poste connecté à Internet.</p>{error&&<div className="error-box" role="alert">{error}</div>}<form onSubmit={e=>{e.preventDefault();work(()=>call('configureOnline',{onlineUrl:url,syncSecret:secret}), 'Relais enregistré et tâche Windows de 20 minutes installée.');}}><div className="fields-grid"><label className="field"><span>Adresse de votre site Vercel</span><input type="url" required value={url} placeholder="https://votre-projet.vercel.app" onChange={e=>setUrl(e.target.value)}/></label><label className="field"><span>Clé de synchronisation du projet</span><input type="password" minLength="32" autoComplete="off" required={!state?.configured} value={secret} placeholder={state?.configured?'Laisser vide pour conserver la clé':''} onChange={e=>setSecret(e.target.value)}/></label></div><div className="inline-controls"><button className="primary" disabled={busy}><Check size={16}/>Configurer le relais</button>{state?.configured&&<button type="button" className="secondary" disabled={busy} onClick={()=>work(()=>call('syncOnline'),'Copie en ligne vérifiée et envoyée.')}><RefreshCw size={16}/>Synchroniser maintenant</button>}</div></form>{state?.configured&&<div className="online-sync-state"><Clock3 size={17}/><span>Dernier transfert réussi : <b>{state.lastSuccess?new Date(state.lastSuccess).toLocaleString('fr-FR'):'En attente du premier envoi'}</b>{state.error&&<small className="amber">{state.error}</small>}</span></div>}<p className="fine-print">Le relais doit rester allumé, connecté au serveur par le réseau local et à Internet, avec sa session Windows ouverte. La copie locale quotidienne sur les cinq PC reste indépendante.</p></section>;
}
